package banking;

import java.awt.*;
import view.modeling.ViewableAtomic;
import view.modeling.ViewableComponent;
import view.modeling.ViewableDigraph;

public class banking extends ViewableDigraph{

public banking(){
    super("banking");
    bankingConstruct();
}

public banking(String nm){
    super(nm);
    bankingConstruct();
}

public void bankingConstruct(){

    addInport("in");
    addOutport("out");
  
    ViewableAtomic c_queue = new customerQueue("Queue");
    ViewableAtomic teller = new teller("Teller");

     add(c_queue);
     add(teller);
     
 	
	addTestInput("in", new customer("C1", 60));
	addTestInput("in", new customer("C2",50));
	addTestInput("in", new customer("C3",100));
	addTestInput("in", new customer("C4",70));
	addTestInput("in", new customer("C5",200));
	addTestInput("in", new customer("C6",50));
	addTestInput("in", new customer("C7",80));
    
     initialize();

     addCoupling(this,"in",c_queue,"in");
     addCoupling(c_queue,"out",teller,"in");
     addCoupling(c_queue,"status",teller,"q_status");
     addCoupling(teller,"next",c_queue,"next");
     addCoupling(teller,"out",this,"out");

}
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(549, 253);
        ((ViewableComponent)withName("Teller")).setPreferredLocation(new Point(243, 93));
        ((ViewableComponent)withName("Queue")).setPreferredLocation(new Point(50, 50));
    }
}
